// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnjbmsblirbxuvzazjtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuamJtc2JsaXJieHV2emF6anRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MzcxOTcsImV4cCI6MjA1ODMxMzE5N30.OxEIrF1ufTbZ_eghrCi_mALO2E_gj2tWhBIusEmz_wg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);